config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get '/about' => 'homes#about', as: 'about'

  resources :post_images, only: [:new, :create, :index, :edit, :update, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy, :show, :index]
  end

  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
    get '/followings' => 'relationships#followings', as: 'followings'
    get '/followers' => 'relationships#followers', as: 'followers'
    resources :notifications, only: [:index]
    delete '/destroy_all' => 'notifications#destroy_all'
  end

  resources :item_images, only: [:new, :create, :index, :show, :edit, :update, :destroy]


  get '/withdraw', to: 'users#withdraw', as: 'withdraw'
  get '/search', to: 'searches#search', as: 'search'

end

app/models/item_image.rb
class ItemImage < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  belongs_to :category
  
    # バリデーション　写真必須
  validates :image, presence: true
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end  
  
  def self.looks(word)
    if word.empty?
      @item_image = ItemImage.all
    else
      @item_image = ItemImage.where("name LIKE?", "%#{word}%")
    end
  end  

end

app/controllers/item_images_controller.rb
class ItemImagesController < ApplicationController
  before_action :authenticate_user!
  def new
    @item_image = ItemImage.new
  end

  def create
    @item_image = ItemImage.new(item_image_params)
    @item_image.user_id = current_user.id
    if @item_image.save
      redirect_to item_images_path
    else
      render :new
    end
  end

  def index
    @user = User.find(current_user.id)
    @item_images = @user.item_images.order(created_at: :desc).page(params[:page])
    @categories = Category.all
    if params[:category_id].present?
      @category = Category.find(params[:category_id])
      @item_images = @category.item_images.where(user: @user).order(created_at: :desc).page(params[:page])
    end
  end

  def show
    @item_image = ItemImage.find(params[:id])
  end

  def edit
    @item_image = ItemImage.find(params[:id])
  end

  def update
    item_image = ItemImage.find(params[:id])
    item_image.update(item_image_params)
    redirect_to item_image_path(item_image.id)
  end

  def destroy
    @item_image = ItemImage.find(params[:id])
    @item_image.destroy
    redirect_to item_images_path
  end

  # アイテム追加時のストロングパラメーター
  private

  def item_image_params
    params.require(:item_image).permit(:image, :name, :brand_name, :category_id)
  end

end

app/helpers/item_images_helper.rb
module ItemImagesHelper
end

app/views/item_images/_index.html.erb
    <% item_images.each do |item_image| %>
      <div class="index-card">
        <p class="center"><%= link_to item_image_path(item_image.id) do %>
          <%= image_tag item_image.get_image(300,250) %>
        <% end %></p>
        <table>
            <tr>
                <td>Category..</td>
                <td><%= item_image.category.name %></td>
            </tr>
            <tr>
                <td>Name.........</td>
                <td><%= item_image.name %></td>
            </tr>
            <tr>
                <td>Brand........</td>
                <td><%= item_image.brand_name %></td>
            </tr>
        </table>
      </div>
    <% end %>

app/views/item_images/edit.html.erb
<div class="flame">
  <h2 class="heading">Edit Item</h2>
  <div class="show-card">
    <%= form_with model: @item_image, url: item_image_path(@item_image.id), method: :patch do |f| %>
      <p class="center"><%= image_tag @item_image.get_image(300,250) %></p>
      <p class="center"><%= f.file_field :image, accept: "image/*" %></p>
      <p class="center">Category</p>
      <p class="center"><%= f.collection_select :category_id, Category.all, :id, :name, autofocus: true, id:"inputCategory_id" %></p>
      <p class="center">Name</p>
      <p class="center"><%= f.text_field :name, autofocus: true, id:"inputName" %></p>
      <p class="center">Brand</p>
      <p class="center"><%= f.text_field :brand_name, autofocus: true, id:"inputBrand_name" %></p>

      <p class="center"><%= f.submit 'Edit', class: "submit" %></p>
    <% end %>
  </div>
</div>

app/views/item_images/index.html.erb
<h2 class="heading">My Closet</h2>
<div class="user-page">
　<div class="sidebar">
    <div>
      <!--アイテム追加ボタン-->
      <%= link_to new_item_image_path, class: "submit link" do %>Add<% end %>

      <!--アイテム検索-->
      <%= form_with url: search_path, local: true, method: :get do |f| %>
        <div class="search-form"><%= f.text_field :word, placeholder: "アイテム名", class: "search-box" %><%= f.submit "Search", class: "search-btn" %></div>
      <% end %>

  　   <!--ジャンル一覧-->
      <table class="category-position">
         <tbody>
           <tr>
             <td>
               <p class="category"><%= link_to "全アイテム", item_images_path , class: "link"%> </p>
             </td>
           </tr>
           <% @categories.each do |category| %>
           <tr>
             <td>
               <p class="category"><%= link_to category.name, item_images_path(category_id: category.id), class: "link" %></p>
             </td>
           </tr>
           <% end %>
         </tbody>
      　</table>
    </div>
  </div>
  <!--ユーザーの投稿一覧-->
  <div class="user-post">
    <% if @item_images.exists? %>
      <h2 class="count">Total..<%= @item_images.total_count %></h2>
    <% else %>
      <h2 class="count">アイテムはありません</h2>
    <% end %>
    <div class="card-wrap">
      <%= render 'index', item_images: @item_images %>
    </div>
  </div>
</div>
<div class="paginate-box">
  <div class="paginate">
     <%= paginate @item_images %>
  </div>
</div>

app/views/item_images/new.html.erb
<div class="flame">
  <h2 class="heading">New Item</h2>
  <div class="show-card">
    <% if @item_image.errors.any? %>
      <p class="center">ERROR:写真が選択されていません</p>
    <% end %>
    <%= form_with model: @item_image do |f| %>
      <p class="center">Image</p>
      <p class="center"><%= f.file_field :image, accept: "image/*" %></p>
      <p class="center">Category</p>
      <p class="center"><%= f.collection_select :category_id, Category.all, :id, :name %></p>
      <p class="center">Name</p>
      <p class="center"><%= f.text_field :name %></p>
      <p class="center">Brand</p>
      <p class="center"><%= f.text_field :brand_name %></p>
      <p class="center"><%= f.submit 'Add', class: "submit" %></p>
    <% end %>
  </div>
</div>

app/views/item_images/show.html.erb
<div class="flame">
  <div class="show-card">


    <p class="center"><%= image_tag @item_image.get_image(300,250) %></p>
    <table>
      <tr>
        <td>Category..</td>
        <td><%= @item_image.category.name %></td>
      </tr>
      <tr>
        <td>Name.........</td>
        <td><%= @item_image.name %></td>
      </tr>
      <tr>
        <td>Brand........</td>
        <td><%= @item_image.brand_name %></td>
      </tr>
      <tr>
        <td>Date.........</td>
        <td><%= @item_image.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
    </table>

    <%= link_to edit_item_image_path(@item_image.id), class: "gray" do %><i class="far fa-edit"></i><% end %>
    <%= link_to item_image_path(@item_image), method: :delete, "data-confirm" => "本当に削除しますか？", class: "gray" do %><i class="far fa-trash-alt"></i><% end %>

  </div>
</div>