config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get '/about' => 'homes#about', as: 'about'

  resources :post_images, only: [:new, :create, :index, :edit, :update, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy, :show, :index]
  end

  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
    get '/followings' => 'relationships#followings', as: 'followings'
    get '/followers' => 'relationships#followers', as: 'followers'
    resources :notifications, only: [:index]
    delete '/destroy_all' => 'notifications#destroy_all'
  end

  resources :item_images, only: [:new, :create, :index, :show, :edit, :update, :destroy]


  get '/withdraw', to: 'users#withdraw', as: 'withdraw'
  get '/search', to: 'searches#search', as: 'search'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :item_images, dependent: :destroy
  # 自分がフォローされる側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通して参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  # 自分が作った通知
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  # 自分宛の通知
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    Relationship.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  # フォロー時の通知
  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ?", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: "follow"
        )
      notification.save if notification.valid?
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.order(created_at: :desc).page(params[:page])
    favorites = Favorite.where(user_id: @user.id).pluck(:post_image_id)
    @favorite_post_images = PostImage.find(favorites)
    @favorite_post_images = Kaminari.paginate_array(@favorite_post_images).page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to  post_images_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to post_images_path
    elsif @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(current_user.id)
    @user.destroy
      redirect_to :root
  end

  def withdraw
  end

  def favorites
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:post_image_id)
    @favorite_post_images = PostImage.find(favorites)
    @favorite_post_images = Kaminari.paginate_array(@favorite_post_images).page(params[:page])
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_favorites.html.erb
<div class="index-position">
  <div class="side-index"></div>
  <div class="card-wrap">
    <% favorite_post_images.each do |post_image| %>
      <div class="index-card">
        <table>
          <td>
            <%= link_to user_path(post_image.user.id), class: "link" do %>
            <%= image_tag post_image.user.get_profile_image(50,50), class: "profile-image" %>
            <% end %>
          </td>
          <td>
            <%= link_to user_path(post_image.user.id), class: "link" do %>
            <%= post_image.user.name %>
            <% end %>
          </td>
        </table>
        <p class="center"><%= link_to post_image_path(post_image.id) do %>
          <%= image_tag post_image.get_image(300,250) %>
          <% end %></p>


        <!--いいね-->
        <div>
          <div id="favorite_buttons_<%= post_image.id %>">
            <%= render "favorites/favorites", post_image: post_image %>
          </div>
          <div>
            コメント<%= post_image.post_comments.count %>件
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="side-index"></div>
</div>
<div class="paginate-box">
  <div class="paginate">
        <%= paginate favorite_post_images %>
  </div>
</div>

app/views/users/_user_info.html.erb
<h2>User Info</h2>
      <dl>
        <dt><%= image_tag user.get_profile_image(100,100), class: "profile-image" %></dt>
        <dd><p class="name"><%= user.name %></p></dd>
      </dl>
      <dl>
        <dt>intr.</dt>
        <dd><%= user.introduction %></dd>
      </dl>
      <dl>
        <dt>following</dt>
        <dd><p class="center"><%= user.followings.count %>　<%= link_to user_followings_path(user) do %><i class="fas fa-clipboard-list"></i><% end %></p></dd>
      </dl>
      <dl>
        <dt>follower</dt>
        <dd><p class="center"><%= user.followers.count %>　<%= link_to user_followers_path(user) do %><i class="fas fa-clipboard-list"></i><% end %></p></dd>
      </dl>
      <dl>
        <dt>posts</dt>
        <dd><p class="center"><%= user.post_images.count %></p></dd>
      </dl>
      <dl>
        <dt>items</dt>
        <dd><p class="center"><%= user.item_images.count %></p></dd>
      </dl>

app/views/users/edit.html.erb
<div class="flame">
  <h2 class="heading">Edit Profile</h2>
  <div class="show-card">
    <% if @user.errors.any? %>
      <p class="center">ご入力いただいたユーザー名は<br>使用できません</p>
    <% end %>

    <%= form_with model: @user do |f| %>
    <p class="center"><%= image_tag @user.get_profile_image(200,200) %></p>
    <p class="center"><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></p>
    <p class="center">UserName</p>
    <p class="center"><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name" %></p>
    <p class="center">Introduction</p>
    <p class="center"><%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction" %></p>
    <p class="center"><%= f.submit 'Edit', class: "submit" %></p>
   <% end %>
    <p class="center"><%= link_to withdraw_path, class: "withdraw link" do %>退会<% end %></p>
    <%= link_to user_path(@user), class: "gray" do %><i class="fas fa-arrow-alt-circle-left"></i><% end %>
  </div>
</div>

app/views/users/favorites.html.erb
<%= render 'favorites', favorite_post_images: @favorite_post_images %>

app/views/users/show.html.erb
<h2 class="heading"><%= @user.name%>'s Page</h2>
  <div class="user-page">
    <!--ユーザー詳細-->
    <div class="sidebar">
      <div id="user_info">
        <%= render "user_info", user: @user %>
      </div>


    <!--フォローボタン-->
    <div id="follow_button">
      <%= render "relationships/follow_button", user: @user %>
    </div>

  <!--編集リンク-->
     <div>
       <% if @user == current_user %>
         <p><%= link_to edit_user_path(@user),class: "submit link" do %>Edit<% end %></p>

       <% end %>
     </div>

    </div>
    <div class="user-post">
      <!--タブ部分-->
      <ul class="tab-list list-unstyled">
        <li class="tab tab-active">
          <p class="center"><%= @user.name%>'s Posts</p>
        </li>
        <li class="tab">
          <p class="center"><%= @user.name%>'s Favorites</p>
        </li>
      </ul>
      <!--タブで選択された要素部分-->
      <div class="tabbox-contents">
        <div class="tabbox box-show">
          <%= render 'post_images/index', post_images: @post_images %>
          <%= paginate @post_images %>
        </div>
        <div class="tabbox">
          <%= render 'favorites', favorite_post_images: @favorite_post_images %>
        </div>
      </div>

    </div>
</div>

app/views/users/withdraw.html.erb
<div class="flame">
  <h2 class="heading">Confirmation</h2>
    <div class="show-card">
　　　<h2 class="center">本当に退会しますか？</h2>
　　　<div></div>
      <p class="center">退会するとプロフィールや今までの投稿、<br>
       クローゼットの記録など、<br>
       全てデータが消えてしまいます。</p>


      <p class="center"><%= link_to user_path(current_user.id), class: "submit link" do %>続ける<% end %></p>
      <p class="center"><%= link_to user_path(current_user.id), method: :delete, "data-confirm" => "本当に退会しますか？", class: "withdraw link" do %>退会<% end %></p>
    </div>
</div>