config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get '/about' => 'homes#about', as: 'about'

  resources :post_images, only: [:new, :create, :index, :edit, :update, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy, :show, :index]
  end

  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
    get '/followings' => 'relationships#followings', as: 'followings'
    get '/followers' => 'relationships#followers', as: 'followers'
    resources :notifications, only: [:index]
    delete '/destroy_all' => 'notifications#destroy_all'
  end

  resources :item_images, only: [:new, :create, :index, :show, :edit, :update, :destroy]


  get '/withdraw', to: 'users#withdraw', as: 'withdraw'
  get '/search', to: 'searches#search', as: 'search'

end

app/models/post_image.rb
class PostImage < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy

  # バリデーション　写真必須
  validates :image, presence: true



  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # いいねの通知
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      post_image_id: id,
      visited_id: user_id,
      action: "favorite"
      )
    notification.save if notification.valid?
  end

  # コメントの通知
  def create_notification_post_comment!(current_user, post_comment_id)
    # 自分以外にコメントしている人を全て取得し、全員に通知を送る
    temp_ids = PostComment.select(:user_id).where(post_image_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_post_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_post_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_post_comment!(current_user, post_comment_id, visited_id)
    # コメントは複数回することが考えられるので、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_image_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: "post_comment"
      )
      # 自分の投稿に対するコメントの場合は、通知済みとする
      if notification.visiter_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
  end

end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_user, only: [:edit, :update, :destroy]

  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
  end

  def index
    @post_images = PostImage.all.order(created_at: :desc).page(params[:page])

  end

  def edit
    @post_image = PostImage.find(params[:id])
  end

  def update
    post_image = PostImage.find(params[:id])
    post_image.update(post_image_params)
    redirect_to post_image_path(post_image.id)
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end


  # 投稿データのストロングパラメーター
  private

  def post_image_params
    params.require(:post_image).permit(:image, :caption)
  end

  def ensure_user
    @post_images = current_user.post_images
    @post_image = @post_images.find_by(id: params[:id])
    redirect_to post_images_path unless @post_image
  end



end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/post_images/_index.html.erb
<div class="card-wrap">
  <% post_images.each do |post_image| %>
  <div class="index-card">
    <table>
      <td>
        <%= link_to user_path(post_image.user.id), class: "link" do %>
        <%= image_tag post_image.user.get_profile_image(50,50), class: "profile-image" %>
        <% end %>
      </td>
      <td>
        <%= link_to user_path(post_image.user.id), class: "link" do %>
        <%= post_image.user.name %>
        <% end %>
      </td>
    </table>
    <p class="center"><%= link_to post_image_path(post_image.id) do %>
      <%= image_tag post_image.get_image(300,250) %>
    <% end %></p>


  <!--いいね-->
    <div>
      <div id="favorite_buttons_<%= post_image.id %>">
        <%= render "favorites/favorites", post_image: post_image %>
      </div>
      <div>
      コメント<%= post_image.post_comments.count %>件
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/post_images/edit.html.erb
<div class="flame">
  <h2 class="heading">Edit</h2>
  <div class="show-card">

    <%= form_with model: @post_image, url: post_image_path(@post_image.id), method: :patch do |f| %>
      <p class="center"><%= image_tag @post_image.get_image(300,250) %></p>
      <p class="center">Caption</p>
      <p class="center"><%= f.text_area :caption %></p>

      <p class="center"><%= f.submit 'Repost', class: "submit" %></p>

    <% end %>
    <%= link_to post_image_path(@post_image.id), class: "gray" do %><i class="fas fa-arrow-alt-circle-left"></i><% end %>
  </div>
</div>

app/views/post_images/index.html.erb
<h2 class="heading">OOTD</h2>
  <div class="index-position">
    <div class="side-index"></div>
        <%= render 'index', post_images: @post_images %>
    <div class="side-index"></div>
  </div>
  <div class="paginate-box">
    <div class="paginate">
        <%= paginate @post_images %>
    </div>
  </div>

app/views/post_images/new.html.erb
<div class="flame">
<h2 class="heading">New Post</h2>
<div class="show-card">
  <% if @post_image.errors.any? %>
   <p class="center">ERROR:写真が選択されていません</p>

  <% end %>
  <%= form_with model: @post_image do |f| %>
    <p class="center">Image</p>
      <p class="center"><%= f.file_field :image, accept: "image/*" %></p>
    <p class="center">Caption</p>
      <p class="center"><%= f.text_area :caption %></p>
    <p class="center"><%= f.submit 'Post', class: "submit" %></p>
  <% end %>
</div>
</div>

app/views/post_images/show.html.erb
<div class="flame">
  <div class="show-card">
    <table>
      <td>
        <%= link_to user_path(@post_image.user.id), class: "link" do %>
        <%= image_tag @post_image.user.get_profile_image(50,50), class: "profile-image" %>
        <% end %>
      </td>
      <td>
        <%= link_to user_path(@post_image.user.id), class: "link" do %>
        <%= @post_image.user.name %>
        <% end %>
      </td>
    </table>
    <p class="center"><%= image_tag @post_image.get_image(300,250) %></p>
    <p><%= @post_image.caption %></p>
    <%= @post_image.created_at.strftime('%Y/%m/%d') %>



  <!--いいね-->
    <div id="favorite_buttons_<%= @post_image.id %>">
      <%= render "favorites/favorites", post_image: @post_image %>
    </div>
    <div>
      コメント<%= @post_image.post_comments.count %>件
    </div>

    <!--コメント件数、コメントフォームへのリンク-->
　　<p><%= link_to post_image_post_comments_path(@post_image.id), class: "submit link" do %>コメントする/見る<% end %>
    </p>



    <!--編集・削除リンク　投稿者にのみ表示-->
    <div>
      <%= link_to post_images_path, class: "gray" do %><i class="fas fa-arrow-alt-circle-left"></i><% end %>
   <% if @post_image.user == current_user %>
      <%= link_to edit_post_image_path(@post_image.id), class: "gray" do %><i class="far fa-edit"></i><% end %>
      <%= link_to post_image_path(@post_image), method: :delete, "data-confirm" => "本当に削除しますか？", class: "gray" do %><i class="far fa-trash-alt"></i><% end %>
   <% end %>
    </div>
  </div>
</div>